/* Auto-generated by scripts/build-format-lifecycle-iife.mjs — do not edit by hand. */
var WLFL = (() => {
  var __defProp = Object.defineProperty;
  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
  var __getOwnPropNames = Object.getOwnPropertyNames;
  var __hasOwnProp = Object.prototype.hasOwnProperty;
  var __export = (target, all) => {
    for (var name in all)
      __defProp(target, name, { get: all[name], enumerable: true });
  };
  var __copyProps = (to, from, except, desc) => {
    if (from && typeof from === "object" || typeof from === "function") {
      for (let key of __getOwnPropNames(from))
        if (!__hasOwnProp.call(to, key) && key !== except)
          __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
    }
    return to;
  };
  var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

  // src/formatLifecycleProfileRuntime.entry.mjs
  var formatLifecycleProfileRuntime_entry_exports = {};
  __export(formatLifecycleProfileRuntime_entry_exports, {
    profileCountryLifecycleMktFmtMult: () => profileCountryLifecycleMktFmtMult2
  });

  // data/formatLifecycle.v1.json
  var formatLifecycle_v1_default = {
    version: 1,
    description: "National format lifecycle catalog (v1 diagnostic). Authoring source for formatLifecycleCore.js \u2014 not loaded by gameplay.",
    nationalFormats: {
      TOP40: {
        lane: "hits",
        emergence: 1955,
        peak: 1982,
        plateauEnd: 1992,
        declineEnd: 2020,
        modernRetention: 0.25,
        declineSteepness: 0.85,
        floor: 0.08,
        notes: "CHR umbrella; historically dominant ~1980; fragments to HOT_AC/RHYTHMIC"
      },
      HOT_AC: {
        lane: "hits",
        canonicalFamily: "ADULT",
        diagnosticLane: "hits",
        crossFamilyLaneAllowed: true,
        emergence: 1988,
        peak: 2004,
        plateauEnd: 2012,
        declineEnd: 2026,
        modernRetention: 0.55,
        declineSteepness: 0.55,
        floor: 0.1,
        notes: "Canonical family ADULT (formatFamilies.v1.json). Diagnostic lane hits for CHR-bucket / modernChrPressure cross-tags \u2014 not a taxonomy error."
      },
      ADULT_CONTEMP: {
        lane: "ac",
        emergence: 1970,
        peak: 1990,
        plateauEnd: 2005,
        declineEnd: 2026,
        modernRetention: 0.65,
        declineSteepness: 0.35,
        floor: 0.12,
        notes: "AC / soft rock workhorse 35-54"
      },
      OLDIES: {
        lane: "heritage",
        emergence: 1975,
        peak: 2e3,
        plateauEnd: 2005,
        declineEnd: 2015,
        modernRetention: 0.35,
        declineSteepness: 0.72,
        floor: 0.05,
        notes: "50s/60s gold; aligns FORMAT_SUNSET peak 2000 / dead 2015; rebrands toward Classic Hits"
      },
      CLASSIC_HITS: {
        lane: "heritage",
        emergence: 1995,
        peak: 2010,
        plateauEnd: 2018,
        declineEnd: 2026,
        modernRetention: 0.5,
        declineSteepness: 0.5,
        floor: 0.08,
        notes: "Oldies successor; demo aging 2010+"
      },
      CLASSIC_ROCK: {
        lane: "rock",
        emergence: 1985,
        peak: 2e3,
        plateauEnd: 2015,
        declineEnd: 2026,
        modernRetention: 0.75,
        declineSteepness: 0.3,
        floor: 0.15,
        notes: "Heritage rock; slow national fade"
      },
      ALBUM_ROCK: {
        lane: "rock",
        emergence: 1970,
        peak: 1982,
        plateauEnd: 1990,
        declineEnd: 2005,
        modernRetention: 0.35,
        declineSteepness: 0.75,
        floor: 0.06,
        notes: "AOR peak late 70s; AM collapse first"
      },
      COUNTRY: {
        lane: "country",
        emergence: 1960,
        peak: 2005,
        plateauEnd: 2015,
        declineEnd: 2026,
        modernRetention: 0.8,
        declineSteepness: 0.25,
        floor: 0.18,
        notes: "Second peak 1990s-2000s; national stickiness high; local coastal variance"
      },
      NEWS_TALK: {
        lane: "spoken",
        emergence: 1985,
        peak: 2012,
        plateauEnd: 2020,
        declineEnd: 2026,
        modernRetention: 0.85,
        declineSteepness: 0.2,
        floor: 0.2,
        notes: "AM to FM; podcast drag post-2015"
      },
      SPORTS_TALK: {
        lane: "spoken",
        emergence: 1990,
        peak: 2015,
        plateauEnd: 2022,
        declineEnd: 2026,
        modernRetention: 0.8,
        declineSteepness: 0.25,
        floor: 0.12,
        notes: "Team-market coupled"
      },
      PERSONALITY_TALK: {
        lane: "spoken",
        emergence: 1990,
        peak: 2005,
        plateauEnd: 2012,
        declineEnd: 2026,
        modernRetention: 0.48,
        declineSteepness: 0.45,
        floor: 0.08,
        notes: "FM hot talk / lifestyle; syndication peak 2000s; post-podcast fragmentation"
      },
      ALL_NEWS: {
        lane: "spoken",
        emergence: 1990,
        peak: 2e3,
        plateauEnd: 2008,
        declineEnd: 2018,
        modernRetention: 0.3,
        declineSteepness: 0.8,
        floor: 0.04,
        notes: "Few metros sustain; edu/coastal"
      },
      PUBLIC: {
        lane: "public",
        emergence: 1970,
        peak: 2020,
        plateauEnd: null,
        declineEnd: 2060,
        modernRetention: 0.95,
        declineSteepness: 0,
        floor: 0.2,
        notes: "Aggregate NCE lane; gradual growth especially educated metros"
      },
      SPANISH: {
        lane: "ethnic",
        emergence: 1975,
        peak: 2024,
        plateauEnd: null,
        declineEnd: 2060,
        modernRetention: 0.95,
        declineSteepness: 0,
        floor: 0.15,
        notes: "Demographic-driven growth"
      },
      SOUL_RNB: {
        lane: "urban",
        emergence: 1965,
        peak: 1978,
        plateauEnd: 1990,
        declineEnd: 2005,
        modernRetention: 0.42,
        declineSteepness: 0.55,
        floor: 0.08,
        notes: "AM soul heritage; disco/funk peak; yields share to Urban Contemporary on FM"
      },
      URBAN_CONTEMP: {
        lane: "urban",
        emergence: 1970,
        peak: 1998,
        plateauEnd: 2010,
        declineEnd: 2026,
        modernRetention: 0.55,
        declineSteepness: 0.45,
        floor: 0.1,
        notes: "FM migration from AM soul"
      },
      RHYTHMIC: {
        lane: "hits",
        emergence: 1995,
        peak: 2010,
        plateauEnd: 2016,
        declineEnd: 2026,
        modernRetention: 0.5,
        declineSteepness: 0.55,
        floor: 0.08,
        notes: "CHR sub-lane"
      },
      AAA: {
        lane: "aaa",
        emergence: 1985,
        peak: 2012,
        plateauEnd: 2020,
        declineEnd: 2026,
        modernRetention: 0.6,
        declineSteepness: 0.35,
        floor: 0.1,
        notes: "Later emergence; edu/fragmented FM"
      },
      ALT_ROCK: {
        lane: "aaa",
        emergence: 1988,
        peak: 1998,
        plateauEnd: 2008,
        declineEnd: 2020,
        modernRetention: 0.45,
        declineSteepness: 0.6,
        floor: 0.06,
        notes: "Select markets; post-peak niche"
      },
      GOSPEL: {
        lane: "religious",
        emergence: 1965,
        peak: 2e3,
        plateauEnd: 2012,
        declineEnd: 2026,
        modernRetention: 0.55,
        declineSteepness: 0.4,
        floor: 0.1,
        notes: "Commercial gospel; regional"
      },
      CCM: {
        lane: "religious",
        emergence: 1980,
        peak: 2008,
        plateauEnd: 2018,
        declineEnd: 2026,
        modernRetention: 0.65,
        declineSteepness: 0.3,
        floor: 0.12,
        notes: "HD/translator era widens footprint post-2004"
      },
      MOR: {
        lane: "heritage",
        emergence: 1960,
        peak: 1976,
        plateauEnd: 1985,
        declineEnd: 1998,
        modernRetention: 0.15,
        declineSteepness: 0.95,
        floor: 0.03,
        notes: "Steep decline; overlaps legacy FORMAT_SUNSET"
      },
      ADULT_STANDARDS: {
        lane: "heritage",
        emergence: 1965,
        peak: 1980,
        plateauEnd: 1990,
        declineEnd: 2005,
        modernRetention: 0.2,
        declineSteepness: 0.9,
        floor: 0.04,
        notes: "Standards / nostalgia AM-FM"
      },
      BEAUTIFUL_MUSIC: {
        lane: "heritage",
        emergence: 1965,
        peak: 1980,
        plateauEnd: 1988,
        declineEnd: 1995,
        modernRetention: 0.1,
        declineSteepness: 0.98,
        floor: 0.02,
        notes: "Extinct by 1995 in gameplay"
      }
    },
    laneInteraction: {
      hits: {
        youthMusicDecayTraitWeight: 0.4,
        eduAccelDeclinePost2005: 0.12
      },
      country: {
        coastalResistanceTraitWeight: 0.35,
        modernRetentionModifierKey: "countryRetention"
      },
      public: {
        educationBoostTraitWeight: 0.45,
        publicAffinityTraitWeight: 0.5
      },
      aaa: {
        educationBoostTraitWeight: 0.35,
        fragmentationTraitWeight: 0.2
      },
      ethnic: {
        spanishGrowthTraitWeight: 0.55
      },
      spoken: {
        spokenWordTraitWeight: 0.4,
        sportsInventoryTraitWeight: 0.25
      },
      religious: {
        hdTranslatorBoostAfter: 2004,
        hdTranslatorBoostMax: 0.08,
        churchTraitWeight: 0.35
      },
      urban: {
        urbanResistanceTraitWeight: 0.25
      },
      rock: {
        fragmentationTraitWeight: 0.15
      },
      ac: {
        coastalResistanceTraitWeight: 0.1
      },
      heritage: {
        coastalResistanceTraitWeight: 0.05
      }
    },
    traitToModifierBoost: {
      publicRadioStrength: { PUBLIC: 0.35, AAA: 0.1 },
      spanishLanguageStrength: { SPANISH: 0.45 },
      countryStrength: { COUNTRY: 0.4 },
      aaaAlternativeStrength: { AAA: 0.35, ALT_ROCK: 0.2 },
      spokenWordStrength: { NEWS_TALK: 0.3, ALL_NEWS: 0.15 },
      sportsStrength: { SPORTS_TALK: 0.35 },
      gospelStrength: { GOSPEL: 0.25 },
      ccmStrength: { CCM: 0.3 },
      urbanContemporaryStrength: { URBAN_CONTEMP: 0.3, RHYTHMIC: 0.15, SOUL_RNB: 0.12 },
      blackMusicStrength: { SOUL_RNB: 0.2, URBAN_CONTEMP: 0.15, GOSPEL: 0.1 },
      chrResistance: { TOP40: -0.12, HOT_AC: -0.08 },
      modernMusicSubstitution: { TOP40: -0.1, HOT_AC: -0.06, RHYTHMIC: -0.06 }
    },
    marketProfiles: {
      portland: {
        comment: "Design persona \u2014 weak modern country, strong public/AAA",
        formatModifiers: {
          COUNTRY: { historicStrength: 0.72, modernRetention: 0.38 },
          AAA: { historicStrength: 0.55, modernRetention: 0.78 },
          PUBLIC: { historicStrength: 0.5, modernRetention: 0.85 }
        }
      },
      nashville: {
        comment: "Design persona \u2014 strong country retention",
        formatModifiers: {
          COUNTRY: { historicStrength: 0.95, modernRetention: 0.92 }
        }
      },
      phoenix: {
        comment: "DIAG_ONLY \u2014 moderate country, Spanish growth",
        formatModifiers: {
          COUNTRY: { historicStrength: 0.58, modernRetention: 0.62 },
          SPANISH: { historicStrength: 0.5, modernRetention: 0.88 }
        }
      }
    }
  };

  // src/formatLifecycleProfileRuntime.js
  function _clamp01(x) {
    return Math.max(0, Math.min(1, Number(x) || 0));
  }
  function _smoothstep(a, b, x) {
    const t = _clamp01((x - a) / Math.max(1e-9, b - a));
    return t * t * (3 - 2 * t);
  }
  function profileCountryLifecycleMktFmtMult(marketId, year, catalog) {
    if (marketId !== "portland") return 1;
    const profileMod = catalog?.marketProfiles?.portland?.formatModifiers?.COUNTRY;
    const nationalSpec = catalog?.nationalFormats?.COUNTRY;
    if (!profileMod || !nationalSpec) return 1;
    const profileRetention = Number(profileMod.modernRetention);
    const nationalRetention = Number(nationalSpec.modernRetention ?? 0.8);
    if (!Number.isFinite(profileRetention) || profileRetention >= nationalRetention) return 1;
    const y = Math.round(Number(year)) || 1970;
    const peak = nationalSpec.peak ?? 2005;
    const plateauEnd = nationalSpec.plateauEnd ?? 2015;
    const declineEnd = nationalSpec.declineEnd ?? 2026;
    let nationalDecline = 0;
    if (y > plateauEnd) {
      nationalDecline = _smoothstep(plateauEnd, declineEnd, y);
    } else if (y > peak) {
      nationalDecline = _smoothstep(peak, plateauEnd, y) * 0.35;
    }
    if (nationalDecline < 0.02) return 1;
    const retentionRatio = profileRetention / Math.max(0.12, nationalRetention);
    const damp = 1 - 0.48 * nationalDecline * (1 - retentionRatio);
    return Math.max(0.72, Math.min(1.06, damp));
  }

  // src/formatLifecycleProfileRuntime.entry.mjs
  function profileCountryLifecycleMktFmtMult2(marketId, year) {
    return profileCountryLifecycleMktFmtMult(marketId, year, formatLifecycle_v1_default);
  }
  return __toCommonJS(formatLifecycleProfileRuntime_entry_exports);
})();

;(function(){
  var g=typeof globalThis!=='undefined'?globalThis:typeof window!=='undefined'?window:{};
  g.__wlProfileCountryLifecycleMktFmtMult=WLFL.profileCountryLifecycleMktFmtMult;
})();
